In [24]:
import pandas as pd
import numpy as np

global_data = pd.read_csv('covid_19_series.csv')

global_data.head()

,Province/States,Country/Region,WHO region,1/21/2020,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,...,5/24/2020,5/25/2020,5/26/2020,5/27/2020,5/28/2020,5/29/2020,5/30/2020,5/31/2020,6/1/2020,6/2/2020
0,Confirmed,Globally,NaN,282.0,314.0,581.0,846.0,1320.0,2014.0,2798.0,...,5204508.0,5304772.0,5404512.0,5488825.0,5593631.0,5701337.0,5817385.0,5934936.0,6057853.0,6194533.0
1,Deaths,Globally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,337687.0,342029.0,343514.0,349095.0,353334.0,357688.0,362705.0,367166.0,371166.0,376320.0
2,Confirmed,China,Western Pacific Region,278.0,309.0,571.0,830.0,1297.0,1985.0,2741.0,...,84525.0,84536.0,84543.0,84544.0,84547.0,84547.0,84565.0,84570.0,84588.0,84597.0
3,Confirmed,Outside of China,NaN,4.0,5.0,10.0,16.0,23.0,29.0,57.0,...,5119983.0,5220236.0,5319969.0,5404281.0,5509084.0,5616790.0,5732820.0,5850366.0,5973265.0,6109936.0
4,Deaths,China,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN,80.0,...,4645.0,4645.0,4645.0,4645.0,4645.0,4645.0,4645.0,4645.0,4645.0,4645.0

In [80]:

global_data_summed = global_data.groupby('Country/Region').sum()
df =global_data_summed
global_data_summed.head(5)

,1/21/2020,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,...,5/24/2020,5/25/2020,5/26/2020,5/27/2020,5/28/2020,5/29/2020,5/30/2020,5/31/2020,6/1/2020,6/2/2020
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10582.0,11094.0,11831.0,12379.0,13016.0,13659.0,14443.0,15094.0,15750.0,16492.0
Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,989.0,1004.0,1029.0,1050.0,1076.0,1099.0,1122.0,1136.0,1143.0,1164.0
Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8113.0,8306.0,8503.0,8697.0,8857.0,8997.0,9134.0,9267.0,9394.0,9513.0
Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,763.0,763.0,763.0,763.0,763.0,764.0,764.0,764.0,764.0,765.0
Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,60.0,69.0,69.0,71.0,71.0,73.0,81.0,84.0,86.0,86.0

In [25]:
countries_plot = ['Italy', 'Poland', 'France', 'Germany', 'United Kingdom']

start_date = '01/21/2020'
end_date = '06/02/2020'

In [81]:
import matplotlib.pyplot as plt
import datetime

def get_index_from_date(date_string):
    FIRST_DATE = datetime.datetime(2020, 1, 22)
    
    date_list = [int(x) for x in date_string.split('/')]
    date_object = datetime.datetime(date_list[-1], date_list[0], date_list[1])
    
    return (date_object-FIRST_DATE).days 

dates = list(df)[1:]

start_index = get_index_from_date(start_date)
end_index = get_index_from_date(end_date)

x_values = dates[start_index:end_index+1]


for country in countries_plot:
    country_df = df[df['Country/Region'] == country]
    y_values = [int(country_df[col] for col in x_values)]
    plt.plot(x_values, y_values, label=country)
    
plt.title('Confirmed Cases Over Time')
skip = max(len(x_values)//5, 1) # Helps ensure we don't add too many date tick marks
plt.xticks(x_values[::skip])
plt.xlabel("Date (MM/DD/YY)")
plt.ylabel("Confirmed Cases")
plt.legend()
plt.show()

KeyError: 'Country/Region'